### ISSUE TITLE
warn about unicode

### ISSUE THREAD

**Issue by florianschanda** [florianschanda/miss_hit#85]
MATLAB unicode handling is questionable at best. For example:
```
x = 'MATLAB is 🥔!'
y = 'MATLAB is !'
disp(x)
disp(length(x))
disp(y)
disp(length(y))
```
Will print something quite surprising. For that reason we should warn when encountering anything that looks like unicode in strings and character arrays.

**Comment by apjanke** [comment]
This sounds like a good idea. Would you consider expanding this to complain about any non-ASCII characters in source code, regardless of what encoding the files are in? (I don't know how you're handling/detecting source file encoding.) Since source file encoding is a user-settable option, and until recent versions of Matlab had a system-dependent default, any non-ASCII in source is a potential portability problem. (And Octave still doesn't have its Unicode story figured out yet.)

**Comment by florianschanda** [comment]
The way encoding is dealt with right now is a horrific hack to be honest. For Simulink it's better, but not awesome either.

And yes, having a rule for just ASCII in source is a great idea, and likely the best way to deal with this lunacy :)

**Comment by florianschanda** [comment]
@apjanke I plan to have one additional flag for this rule (by default true), which is to also enforce ascii in comments/continuations.

So by default just ASCII is enforced everywhere; but you can optionally relax it by allowing it in comments. Would that be suitable for your needs?

Not sure if I can auto-fix anything.

**Comment by apjanke** [comment]
Sounds great.

Yeah, I don't know how auto-fixing could be done in a non-destructive manner.

**Comment by florianschanda** [comment]
This will be in the next release. There will be three config options:
* one to turn this on/off
* one to pick a different set than ascii
* one to control if this applies to comments or not

Let me know if there are any issues for you

**Comment by mvanzulli** [comment]
> one to turn this on/off

Which is the config flag to disable this check ?
